/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:573e5534-ca81-4cf8-bcf7-c82ddd2fb117",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_seMqJZrLg",
    "aws_user_pools_web_client_id": "1db176ghm5sn5tdg4bbl81liq2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://i5gqbqoyije55pd6vp3bdnzgwi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
